services:
  # Just the main database
  db:
    image: postgres:18.1
    container_name: dine_map_db
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql

  # Serves vector tiles using MapTiler's tileserver-gl
  tileserver:
    image: maptiler/tileserver-gl
    container_name: dine_map_tileserver
    volumes:
      - ./tileset:/data:Z
    command: -c /data/config.json
    ports:
      - '${TILES_PORT}:8080'

volumes:
  pg_data:
